# Generated by Django 3.2.5 on 2022-02-07 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_message_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='uid',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
