# Generated by Django 3.2.5 on 2022-02-11 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_message_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='uid',
            new_name='username',
        ),
        migrations.AddField(
            model_name='message',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
