# Generated by Django 3.2.5 on 2022-02-11 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20220211_1559'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='username',
        ),
        migrations.AlterField(
            model_name='message',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='message',
            name='image',
            field=models.ImageField(blank=True, default=None, upload_to=''),
            preserve_default=False,
        ),
    ]
