# Generated by Django 3.2.5 on 2022-02-13 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_message_date_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='date_posted',
            field=models.DateField(auto_now_add=True),
        ),
    ]
