# Generated by Django 3.2.5 on 2022-02-16 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_alter_message_likes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
