# Generated by Django 3.2.5 on 2022-02-21 16:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_alter_message_date_posted'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='time_posted',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
