# Generated by Django 3.2.5 on 2022-02-26 05:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0044_remove_like_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniqueid', models.UUIDField(default=uuid.uuid4)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
