# Generated by Django 3.2.5 on 2022-02-26 06:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0048_person_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='friends',
            field=models.ManyToManyField(blank=True, default=None, related_name='friends', to=settings.AUTH_USER_MODEL),
        ),
    ]
