# Generated by Django 3.2.5 on 2022-02-26 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0051_auto_20220226_1247'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
