# Generated by Django 3.2.5 on 2022-02-26 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0052_delete_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
    ]
